# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Use the appropriate VM image

steps:
- script: |
    echo "Checking Java version"
    java -version
    javac -version
  displayName: 'Check Java Installation'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'

- script: |
    java -jar target/my-app-1.0-SNAPSHOT.jar
  displayName: 'Run Java Application'
