trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk maven   # Installs JDK 17 and Maven
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
    export M2_HOME=/usr/share/maven
    echo "JAVA_HOME is set to $JAVA_HOME"
    echo "M2_HOME is set to $M2_HOME"
  displayName: 'Install JDK 17 and Maven'

- script: |
    echo "Running Maven Build"
    mvn clean install               # Command to build your Maven project
  displayName: 'Maven Build'

- script: |
    echo "Running Java Application"
    java -jar target/my-app-1.0-SNAPSHOT.jar    # Command to run the built .jar file
  displayName: 'Run Java Application'
